"""Adding employees table

Revision ID: 1b7768dfc833
Revises: 
Create Date: 2022-07-21 11:42:24.936563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7768dfc833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('priority')
    with op.batch_alter_table('Prodject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creator', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Prodject_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Category', ['category'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['creator'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Priority', ['priority'], ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_task', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_registration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_online', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('about_self', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('super_user', sa.Boolean(), nullable=True))
        batch_op.drop_column('online')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('super_user')
        batch_op.drop_column('about_self')
        batch_op.drop_column('last_online')
        batch_op.drop_column('date_registration')
        batch_op.drop_column('num_task')

    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('priority')
        batch_op.drop_column('deadline')
        batch_op.drop_column('is_finished')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('Prodject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Prodject_author_fkey', 'User', ['author'], ['id'])
        batch_op.drop_column('creator')
        batch_op.drop_column('category')
        batch_op.drop_column('is_open')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    op.create_table('priority',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='priority_pkey')
    )
    op.drop_table('Priority')
    # ### end Alembic commands ###
